### ISSUE TITLE
userOptions.headers is polluted by previous requests headers. Use decorator instead to add headers

### ISSUE THREAD

**Issue by bryanparadis** [nsimmons/koa-better-http-proxy#25]
If you are reusing the returned proxy function and you add headers to the proxy userOptions, the headers object will get polluted [here](https://github.com/nsimmons/koa-better-http-proxy/blob/master/lib/requestOptions.js#L58). The next request will also get the additional headers. 

Freezing userOptions.headers before passing it into proxy(url, userOptions) illicits this stack:

```
TypeError: Cannot add property client-ip, object is not extensible
      at extend (/Users/user/example/node_modules/koa-better-http-proxy/lib/requestOptions.js:15:17)
      at reqHeaders (/Users/user/example/node_modules/koa-better-http-proxy/lib/requestOptions.js:58:13)
      at Object.createRequestOptions [as create] (/Users/user/example/node_modules/koa-better-http-proxy/lib/requestOptions.js:74:14)
      at buildProxyReq (/Users/user/example/node_modules/koa-better-http-proxy/app/steps/buildProxyReq.js:11:41)
      at /Users/user/example/node_modules/koa-better-http-proxy/index.js:29:12
      at _default (/Users/user/example/build/server/main.js:902:23)
      at /Users/user/example/node_modules/koa-mount/index.js:58:11
      at dispatch (/Users/user/example/node_modules/koa-compose/index.js:42:32)
      at ProxyMiddleware (/Users/user/example/build/server/main.js:1054:13)
      at dispatch (/Users/user/example/node_modules/koa-compose/index.js:42:32)

```

Using the proxyReqOptDecorator instead of adding the headers to the userOptions doesn't seem to have this issue. Reusing proxy() may have other sideaffects as well. Just fyi

**Comment by Freezind** [comment]
We encountered this issue too
